name: CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs: 
  build-nucleo-f303re:
    container:
      image: ghcr.io/armmbed/mbed-os-env:master-latest

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [NUCLEO_F303RE]
        profile: [debug]
        

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
          
      -
        name: build-bomberman
        run: |
          set -e
          mbed deploy
          mbed compile -t GCC_ARM -m ${{ matrix.target }} --profile ${{ matrix.profile }}
